### ISSUE TITLE
Slow `loop.first`

### ISSUE THREAD

**Issue by crisward** [straight-shoota/crinja#3] opened 2017-10-08 19:25 UTC
Just found one of my templates running slow. It loops over 60 + items. If I remove a check for `loop.first` the templates drops from a very slow 1.5 seconds, down to 800ms. 

Not sure why it spends half it's time assessing loop.first. I've tried with `loop.index == 0` and it's equally slow.

Also I've notice if I put it in the second part of an `if .. and` expression, the bit after the and is evaluated even if the first one is false.

Hopefully those two issue are easy optimisations. Good work on this engine, really like the idea of run time templates. If I can work either out I'll do a pull request.

**Comment by straight-shoota** [comment] 2017-10-08 19:41
Thanks 👍 

Number two is easy: The process for resolving boolean expressions is just missing the feature of skipping irrelevant branches. But it should be easy to do.

I have however no idea about the speed issue but I'll try to investigate. It might help if you could give me some reproducable code.

**Comment by crisward** [comment] 2017-10-08 19:55
I'll extract it from my project.

**Comment by straight-shoota** [comment] 2017-10-08 20:17
logic operators should be fixed with f45028f

**Comment by crisward** [comment] 2017-10-08 20:27
I have a failing test that I've added to a fork. Would you me to open a pull request, or do you just want to copy it? It's here https://github.com/crisward/crinja/blob/loopspeed/spec/tags/for_spec.cr#L184

I'm getting
```
00:00:00.0300180 #loop one with a string if
00:00:03.3610960 #loop two with a loop.first if
```
I've tried swapping the execution order and the results are the same.

**Comment by crisward** [comment] 2017-10-08 20:38
Thanks for the other update BTW... It's actually had a massive effect on speed, that 800ms page is now 150ms. All those unnecessary evaluations must really add up. 👍

**Comment by straight-shoota** [comment] 2017-10-08 20:39
Yes, if there are expensive operations involved... :D

**Comment by crisward** [comment] 2017-10-08 21:13
I've used apples instruments to try and identify where the time is being used up. Can't say I understand the result, but thought it may help.

<img width="1058" alt="screen shot 2017-10-08 at 22 11 40" src="https://user-images.githubusercontent.com/3109157/31320994-ed1ec8ac-ac75-11e7-9c95-e312985ed82c.png">

**Comment by straight-shoota** [comment] 2017-10-08 21:20
Ah this is great! I have no idea how to get proper profiling under linux...  seems to be much easier on a mac  ;)
Could you please provide a bit more context in the screenshot?

**Comment by crisward** [comment] 2017-10-08 21:28
I've expanded back up to the template render method. 

<img width="1001" alt="screen shot 2017-10-08 at 22 26 06" src="https://user-images.githubusercontent.com/3109157/31321095-e0699bee-ac77-11e7-8b31-27926346f67a.png">

**Comment by crisward** [comment] 2017-10-08 21:34
Here's the other hot path expanded. 
<img width="996" alt="screen shot 2017-10-08 at 22 33 07" src="https://user-images.githubusercontent.com/3109157/31321138-c688505c-ac78-11e7-8c71-88bae0a7799a.png">

**Comment by straight-shoota** [comment] 2017-10-08 21:43
Oh, it's too easy... there was a leftover `logger.debug` wich inspected the ForLoop and thus the iterator array every time `loop.*` was accessed.

**Closed** 2017-10-08 21:45 UTC

**Comment by crisward** [comment] 2017-10-08 21:53
Copied your change here and my test passes. Cool. 
Thanks for the rapid response. Down to 54ms now. All good. 💯
